server:
  port: 8010

spring:
  application:
    name: bank-statements-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/statements_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:saksham12}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
