package com.gdb.aiassistant.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class ChatResponse {
    /** Plain-text reply shown in the chat bubble */
    private String message;

    /** "navigate" | "answer" | "clarify" */
    private String action;

    /** Frontend route to navigate to, e.g. "/loans/apply" */
    private String route;

    /** Human-readable label for the route, e.g. "Apply for Loan" */
    @JsonProperty("route_label")
    private String routeLabel;

    /** Whether the response was generated by Claude or by fallback rules */
    @JsonProperty("ai_generated")
    private boolean aiGenerated;
}
